name: MSTest
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v2.0.1
      - name: Restore NuGet Packages
        run: nuget restore SampleFormsApp.sln
      - name: Build app for release
        run: msbuild SampleFormsApp.sln -t:rebuild -verbosity:diag -property:Configuration=$env:Configuration
        env:
          Configuration: ${{ matrix.configuration }}
      - name: vstest-action
        uses: microsoft/vstest-action@v1.0.0
        with:
          testAssembly: |
            **\${{ matrix.configuration }}\net48\SampleFormApp_Test.dll
            !**\obj\**


