name: MSTest
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        configration: [Debug, Release]
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
      - name: Build app for release
        run: msbuild SampleFormsApp.sln -t:rebuild -verbosity:diag -property:Configuration=Release

